### ISSUE TITLE
Could you please add more support to atari environment?

### ISSUE THREAD

**Issue by THSWind** [BY571/Munchausen-RL#1]
Hello,
Could you please add more support to atari environment? Such as 'BreakoutNoFrameskip-v4', 'BreakoutDeterministic-v4'....

**Comment by BY571** [comment]
hey @THSWind ,
you mean for M-DQN? If so yes, I plan to add Munchausen RL to my [Atari Agent DQN implementations](https://github.com/BY571/DQN-Atari-Agents). But for M-IQN I can tell you it has already Atari support with CNN. If you want check out my repo [IQN and Extensions](https://github.com/BY571/IQN-and-Extensions). 

Hope this helps you a bit for now.

**Comment by THSWind** [comment]
@BY571 
Thank you,
 I’ve seen it([IQN and Extensions](https://github.com/BY571/IQN-and-Extensions)), it can just run "CartPole-v0", I tried it with ‘breakoutNoFrameskip-v4' and another 'deterministic-v4' games, it doesn't work

**Comment by BY571** [comment]
@THSWind  You have to use the script version. Not the notebook. Check the readme for that :)

**Comment by THSWind** [comment]
@BY571  Oh, I found it. Thank you for your patience~. You've done a great job
